// AA 00060 P13: the test faucet's SPL instructions and the Mint layout equal @solana/spl-token 0.4.15's
// (fixtures/spl-instructions.json, generated by evidence/00060-night-market-bridge-wallet/p13/spl-vectors-gen.mjs
// from the 00050 template's copy of spl-token), and a signed transaction assembles as web3.js's does.

import { readFileSync } from 'node:fs';

import { Keypair, PublicKey, Transaction, TransactionInstruction } from '@solana/web3.js';
import nacl from 'tweetnacl';
import { describe, expect, it } from 'vitest';

import {
  MINT_ACCOUNT_BYTES,
  assembleTransaction,
  associatedTokenAddress,
  compileLegacyMessage,
  createAssociatedTokenAccountIdempotentInstruction,
  encodeKey,
  mintToCheckedInstruction,
  parseMintAccount,
  type Instruction,
} from '../src/solana/index.js';

interface VectorIx {
  programId: string;
  keys: { pubkey: string; isSigner: boolean; isWritable: boolean }[];
  data: string;
}
const V = JSON.parse(readFileSync(new URL('./fixtures/spl-instructions.json', import.meta.url), 'utf8')) as {
  mintToChecked: {
    mint: string;
    destination: string;
    authority: string;
    amount: string;
    decimals: number;
    instruction: VectorIx;
  }[];
  createIdempotent: { payer: string; associatedAccount: string; owner: string; mint: string; instruction: VectorIx }[];
  ata: { owner: string; mint: string; address: string }[];
  mintLayout: {
    data: string;
    mintAuthority: string | null;
    supply: string;
    decimals: number;
    isInitialized: boolean;
    freezeAuthority: string | null;
  }[];
};

const asVector = (ix: Instruction): VectorIx => ({
  programId: ix.programId,
  keys: ix.keys,
  data: Buffer.from(ix.data).toString('hex'),
});

describe('the SPL instructions (spl-token 0.4.15 vectors)', () => {
  it('MintToChecked: the same program, accounts and data', () => {
    expect(V.mintToChecked.length).toBeGreaterThan(0);
    for (const v of V.mintToChecked)
      expect(
        asVector(mintToCheckedInstruction(v.mint, v.destination, v.authority, BigInt(v.amount), v.decimals)),
      ).toEqual(v.instruction);
  });

  it('CreateIdempotent: the same program, accounts and data', () => {
    for (const v of V.createIdempotent)
      expect(
        asVector(createAssociatedTokenAccountIdempotentInstruction(v.payer, v.associatedAccount, v.owner, v.mint)),
      ).toEqual(v.instruction);
  });

  it('the associated token address equals getAssociatedTokenAddressSync', () => {
    for (const v of V.ata) expect(associatedTokenAddress(v.owner, v.mint)).toBe(v.address);
  });

  it('parses MintLayout as spl-token encodes it', () => {
    for (const v of V.mintLayout) {
      const data = Uint8Array.from(Buffer.from(v.data, 'hex'));
      expect(data.length).toBe(MINT_ACCOUNT_BYTES);
      expect(parseMintAccount(data)).toEqual({
        mintAuthority: v.mintAuthority,
        supply: BigInt(v.supply),
        decimals: v.decimals,
        isInitialized: v.isInitialized,
        freezeAuthority: v.freezeAuthority,
      });
    }
  });

  it('refuses a malformed mint account and amounts that are not a positive u64', () => {
    expect(() => parseMintAccount(new Uint8Array(81))).toThrow(/82 bytes/);
    const bad = new Uint8Array(82);
    bad[0] = 2;
    expect(() => parseMintAccount(bad)).toThrow(/malformed/);
    const [v] = V.mintToChecked;
    expect(() => mintToCheckedInstruction(v!.mint, v!.destination, v!.authority, 0n, 6)).toThrow(/positive u64/);
    expect(() => mintToCheckedInstruction(v!.mint, v!.destination, v!.authority, 1n << 64n, 6)).toThrow(/positive u64/);
  });
});

describe('assembleTransaction', () => {
  it('equals web3.js serialize() for the faucet transaction signed by two keys', () => {
    const payer = Keypair.fromSeed(new Uint8Array(32).fill(1));
    const other = Keypair.fromSeed(new Uint8Array(32).fill(2));
    const wallet = new PublicKey(new Uint8Array(32).fill(3)).toBase58();
    const mints = [
      new PublicKey(new Uint8Array(32).fill(4)).toBase58(),
      new PublicKey(new Uint8Array(32).fill(5)).toBase58(),
    ];
    const auth = [payer, other];
    const blockhash = encodeKey(new Uint8Array(32).fill(6));
    const ixs: Instruction[] = [];
    mints.forEach((m, i) => {
      const ata = associatedTokenAddress(wallet, m);
      ixs.push(createAssociatedTokenAccountIdempotentInstruction(payer.publicKey.toBase58(), ata, wallet, m));
      ixs.push(mintToCheckedInstruction(m, ata, auth[i]!.publicKey.toBase58(), 1_000_000_000n, 6));
    });
    const message = compileLegacyMessage(payer.publicKey.toBase58(), blockhash, ixs);
    const secret = new Map(auth.map((k) => [k.publicKey.toBase58(), k.secretKey]));
    const sigs = message.accountKeys
      .slice(0, message.numRequiredSignatures)
      .map((k) => nacl.sign.detached(message.bytes, secret.get(k)!));
    const ours = assembleTransaction(message, sigs);

    const tx = new Transaction({ feePayer: payer.publicKey, recentBlockhash: blockhash });
    for (const ix of ixs)
      tx.add(
        new TransactionInstruction({
          programId: new PublicKey(ix.programId),
          keys: ix.keys.map((k) => ({ ...k, pubkey: new PublicKey(k.pubkey) })),
          data: Buffer.from(ix.data),
        }),
      );
    tx.sign(payer, other);
    expect(Buffer.from(ours).toString('hex')).toBe(tx.serialize().toString('hex'));
    expect(() => assembleTransaction(message, sigs.slice(1))).toThrow(/needs 2 signatures/);
  });
});
