// AA 00060 P13 (spec FR-024), the plan's P13 unit tests: the test SPL faucet ("Mint Solana tokens").
//
//   mainnet genesis refused (the registry's, and the RPC's) · a mint not in I-1 refused · an authority
//   mismatch refused (at the check, and per claim after admission) · the period limit · the claim record
//   survives a restart (claimed, and a pending one reconciled) · the amount in each mint's decimals ·
//   the keys never in the logs (nor in results, refusals or the offer) · the C2 pattern (an unsigned claim
//   charges the CLIENT, never the wallet it names) · the one transaction fits and pays from the faucet key.
//
// Every key here is a throwaway generated by the test. The Solana side is the shared mock RPC
// (test/mocks/solana-rpc.ts: it checks every signature and blockhash) plus a small emulator of the two
// instructions the faucet sends, so balances can be read back.

import { chmodSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import nacl from 'tweetnacl';
import { afterAll, describe, expect, it } from 'vitest';

import {
  SOLANA_MAINNET_BETA_GENESIS_HASH,
  type JobView,
  type SplFaucetInfo,
  type SplFaucetResult,
} from '@nightmarket/core';
import { BridgeRegistry, type BridgeEntry } from '@nightmarket/core/bridge';
import {
  ASSOCIATED_TOKEN_PROGRAM_ID,
  TOKEN_PROGRAM_ID,
  associatedTokenAddress,
  decodeKey,
  encodeKey,
  parseMintAccount,
  splitTransaction,
} from '@nightmarket/core/solana';

import { asFetch, json } from '../../test/mocks/http.js';
import { mockSolanaRpc, type MockSolanaRpc } from '../../test/mocks/solana-rpc.js';
import { defaultCatalogue, withSplFaucet } from '../src/actions/catalogue.js';
import { ConfigError, loadConfig } from '../src/config.js';
import { SplFaucetClaims } from '../src/faucet/claims.js';
import { FaucetKeysError, modeTooOpen, parseFaucetKeys, secretForms, type FaucetKey } from '../src/faucet/keys.js';
import { FaucetSolanaRpc, type FaucetFetch } from '../src/faucet/solana-rpc.js';
import { FaucetConfigError, SplFaucet, claimInstructions, faucetTokens } from '../src/faucet/spl-faucet.js';
import { Redactor, createLogger } from '../src/log.js';
import { keysFileText, planKeysFile } from '../src/tools/spl-faucet-keys.js';
import { harness, newWallet, post, signedBody, silentLog } from './harness.js';

const DAY = 86_400;
const dirs: string[] = [];
afterAll(() => {
  for (const d of dirs) rmSync(d, { recursive: true, force: true });
});
const tempDir = () => {
  const d = mkdtempSync(join(tmpdir(), 'aa00060-splfaucet-'));
  dirs.push(d);
  return d;
};

/** A throwaway authority key, generated now. */
const newKey = (): FaucetKey => {
  const kp = nacl.sign.keyPair();
  return { publicKey: encodeKey(kp.publicKey), secretKey: kp.secretKey };
};
const randomAddress = () => encodeKey(nacl.randomBytes(32));

/** A classic SPL mint account's data (82 bytes). */
function mintData(authority: string | null, decimals: number): Uint8Array {
  const d = new Uint8Array(82);
  const v = new DataView(d.buffer);
  if (authority) {
    v.setUint32(0, 1, true);
    d.set(decodeKey(authority), 4);
  }
  d[44] = decimals;
  d[45] = 1;
  return d;
}

// ── a mock chain that runs the faucet's two instructions ─────────────────────────────────────────────

interface Decoded {
  signers: number;
  keys: string[];
  ixs: { program: string; accounts: string[]; data: Uint8Array }[];
}
function decodeMessage(m: Uint8Array): Decoded {
  let at = 0;
  const vec = () => {
    let n = 0;
    let shift = 0;
    for (;;) {
      const b = m[at++]!;
      n |= (b & 0x7f) << shift;
      if ((b & 0x80) === 0) return n;
      shift += 7;
    }
  };
  const signers = m[0]!;
  at = 3;
  const nk = vec();
  const keys = Array.from({ length: nk }, (_, i) => encodeKey(m.slice(at + 32 * i, at + 32 * (i + 1))));
  at += 32 * nk + 32;
  const ni = vec();
  const ixs: Decoded['ixs'] = [];
  for (let i = 0; i < ni; i++) {
    const program = keys[m[at++]!]!;
    const na = vec();
    const accounts = Array.from(m.slice(at, at + na)).map((x) => keys[x]!);
    at += na;
    const nd = vec();
    ixs.push({ program, accounts, data: m.slice(at, at + nd) });
    at += nd;
  }
  return { signers, keys, ixs };
}

interface Chain {
  rpc: MockSolanaRpc;
  /** The next sends: accepted by the RPC but never land (status null). */
  drop: boolean;
  /** The next sends are refused by the RPC with this message (preflight). */
  refuse: string | null;
  balance(owner: string, mint: string): bigint;
  fetch: FaucetFetch;
}

function mockChain(genesisHash?: string): Chain {
  const rpc = mockSolanaRpc(genesisHash ? { genesisHash } : {});
  const inner = rpc.handler;
  const c: Chain = {
    rpc,
    drop: false,
    refuse: null,
    balance: (owner, mint) => rpc.tokenBalances.get(associatedTokenAddress(owner, mint))?.amount ?? 0n,
    fetch: asFetch(async (req) => {
      const text = await req.text();
      const body = JSON.parse(text) as { id: unknown; method: string; params?: unknown[] };
      const again = () => inner(new Request(req.url, { method: 'POST', body: text }));
      if (body.method !== 'sendTransaction') return again();
      if (c.refuse) return json({ jsonrpc: '2.0', id: body.id, error: { code: -32002, message: c.refuse } });
      const res = await again();
      const out = (await res.clone().json()) as { result?: string };
      if (!out.result) return res;
      const wire = Uint8Array.from(Buffer.from(String(body.params![0]), 'base64'));
      const { problem, apply } = runFaucetTx(rpc, wire);
      if (problem || c.drop) rpc.sent.pop();
      else apply();
      if (problem)
        return json({
          jsonrpc: '2.0',
          id: body.id,
          error: { code: -32002, message: `Transaction simulation failed: ${problem}` },
        });
      return res;
    }),
  };
  return c;
}

/** Validate the ATA CreateIdempotent and MintToChecked instructions (nothing else allowed); `apply` lands them. */
function runFaucetTx(rpc: MockSolanaRpc, wire: Uint8Array): { problem: string | null; apply: () => void } {
  const problem = (p: string) => ({ problem: p, apply: () => {} });
  const d = decodeMessage(splitTransaction(wire).message);
  const signers = new Set(d.keys.slice(0, d.signers));
  const effects: (() => void)[] = [];
  const created = new Set<string>();
  for (const ix of d.ixs) {
    if (ix.program === ASSOCIATED_TOKEN_PROGRAM_ID && ix.data.length === 1 && ix.data[0] === 1) {
      const [payer, ata, owner, mint] = ix.accounts;
      if (!signers.has(payer!)) return problem('the payer did not sign');
      if (associatedTokenAddress(owner!, mint!) !== ata) return problem('not the associated token address');
      const m = rpc.accounts.get(mint!);
      if (!m) return problem('no such mint');
      if (!rpc.accounts.has(ata!) && !created.has(ata!)) {
        created.add(ata!);
        const decimals = parseMintAccount(m.data!).decimals;
        effects.push(() => {
          rpc.accounts.set(ata!, { owner: TOKEN_PROGRAM_ID, data: new Uint8Array(165) });
          rpc.tokenBalances.set(ata!, { amount: 0n, decimals });
        });
      }
    } else if (ix.program === TOKEN_PROGRAM_ID && ix.data.length === 10 && ix.data[0] === 14) {
      const [mint, dest, authority] = ix.accounts;
      const m = rpc.accounts.get(mint!);
      if (!m) return problem('no such mint');
      const parsed = parseMintAccount(m.data!);
      if (!signers.has(authority!)) return problem('missing required signature');
      if (parsed.mintAuthority !== authority) return problem('owner does not match');
      if (ix.data[9] !== parsed.decimals) return problem('decimals mismatch');
      if (!rpc.accounts.has(dest!) && !created.has(dest!)) return problem('invalid account data');
      const amount = new DataView(ix.data.buffer, ix.data.byteOffset).getBigUint64(1, true);
      effects.push(() => {
        const b = rpc.tokenBalances.get(dest!)!;
        rpc.tokenBalances.set(dest!, { ...b, amount: b.amount + amount });
      });
    } else return problem('an instruction the faucet does not send');
  }
  return {
    problem: null,
    apply: () => {
      for (const e of effects) e();
    },
  };
}

// ── the faucet under test ────────────────────────────────────────────────────────────────────────────

const entry = (symbol: string, splMint: string, decimals: number): BridgeEntry => ({
  colour: encodeHex(nacl.randomBytes(32)),
  splMint,
  bridgeContract: encodeHex(nacl.randomBytes(32)),
  bridgeProgram: randomAddress(),
  bridgeApi: 'http://127.0.0.1:18080',
  name: `Test ${symbol}`,
  symbol,
  decimals,
});
const encodeHex = (b: Uint8Array) => Buffer.from(b).toString('hex');

function setup(
  o: {
    registryGenesis?: string;
    rpcGenesis?: string;
    file?: string | null;
    amount?: string;
    perClient?: number;
    cap?: number;
    chain?: Chain;
    keys?: { x: FaucetKey; y: FaucetKey; mx: string; my: string };
    clock?: { now: number };
    log?: ReturnType<typeof silentLog>;
    pollMs?: number;
    confirmTimeoutMs?: number;
  } = {},
) {
  const ch = o.chain ?? mockChain(o.rpcGenesis);
  const k = o.keys ?? { x: newKey(), y: newKey(), mx: randomAddress(), my: randomAddress() };
  if (!ch.rpc.accounts.has(k.mx)) {
    ch.rpc.accounts.set(k.mx, { owner: TOKEN_PROGRAM_ID, data: mintData(k.x.publicKey, 6) });
    ch.rpc.accounts.set(k.my, { owner: TOKEN_PROGRAM_ID, data: mintData(k.y.publicKey, 9) });
  }
  const registry = new BridgeRegistry('undeployed', o.registryGenesis ?? ch.rpc.genesisHash, [
    entry('X', k.mx, 6),
    entry('Y', k.my, 9),
  ]);
  const clock = o.clock ?? { now: 1_800_000_000 };
  const log = o.log ?? silentLog();
  const claims = new SplFaucetClaims({ file: o.file ?? null, periodSeconds: DAY, now: () => clock.now });
  const faucet = new SplFaucet({
    registry,
    keys: new Map([
      [k.mx, k.x],
      [k.my, k.y],
    ]),
    rpc: new FaucetSolanaRpc('http://solana-rpc.test', ch.fetch),
    claims,
    amountWhole: o.amount ?? '1000',
    periodSeconds: DAY,
    claimsPerPeriod: o.cap ?? 200,
    perClientPerPeriod: o.perClient ?? 3,
    log,
    now: () => clock.now,
    pollMs: o.pollMs ?? 1,
    confirmTimeoutMs: o.confirmTimeoutMs ?? 150,
    recheckSeconds: 0,
  });
  const client = { address: '198.51.100.7' };
  const h = harness({
    catalogue: withSplFaucet(defaultCatalogue(), {
      admit: ({ payload, client: c }) => faucet.admit(payload, c ?? 'unknown'),
      executor: faucet.executor(),
    }),
    splFaucet: (w) => faucet.info(w),
    clientAddress: () => client.address,
  });
  const claim = async (wallet: string) => {
    const res = await post(h, 'spl-faucet', { payload: { wallet } });
    const body = (await res.json()) as { job?: JobView; error?: { code: string; message: string; detail?: string } };
    if (res.status !== 202)
      return { status: res.status, error: body.error!, retryAfter: res.headers.get('retry-after') };
    await h.queue.settled(body.job!.requestId);
    const job = ((await (await h.app.request(`/v1/jobs/${body.job!.requestId}`)).json()) as { job: JobView }).job;
    return { status: 202, job };
  };
  const info = async (wallet?: string) =>
    (await (await h.app.request(`/v1/spl-faucet${wallet ? `?wallet=${wallet}` : ''}`)).json()) as SplFaucetInfo;
  return { ch, k, registry, faucet, claims, h, clock, log, client, claim, info };
}

const okResult = (r: Awaited<ReturnType<ReturnType<typeof setup>['claim']>>): SplFaucetResult => {
  if (!('job' in r) || !r.job) throw new Error(`refused: ${JSON.stringify(r)}`);
  if (r.job.state !== 'succeeded') throw new Error(`job ${r.job.state}: ${JSON.stringify(r.job.error)}`);
  return r.job.result as unknown as SplFaucetResult;
};

// ── the tests ────────────────────────────────────────────────────────────────────────────────────────

describe('the test SPL faucet: a claim', () => {
  it('mints 1,000 X and 1,000 Y to a fresh wallet in ONE transaction paid by the faucet key, creating its accounts', async () => {
    const s = setup();
    await s.faucet.check();
    expect(s.faucet.current.kind).toBe('ready');
    const wallet = randomAddress();
    const offer = await s.info(wallet);
    expect(offer).toMatchObject({ enabled: true, periodHours: 24 });
    expect(offer.claim).toBeUndefined();
    expect(offer.tokens.map((t) => [t.symbol, t.amount])).toEqual([
      ['X', '1000000000'],
      ['Y', '1000000000000'],
    ]);
    const r = okResult(await s.claim(wallet));
    expect(s.ch.rpc.sent).toHaveLength(1);
    expect(r.signature).toBe(s.ch.rpc.sent[0]!.signature);
    // The fee payer (first signer) is X's authority; both authorities sign; the wallet does not.
    const d = decodeMessage(s.ch.rpc.sent[0]!.message);
    expect(d.keys.slice(0, d.signers).sort()).toEqual([s.k.x.publicKey, s.k.y.publicKey].sort());
    expect(d.keys[0]).toBe(s.k.x.publicKey);
    expect(d.keys.slice(0, d.signers)).not.toContain(wallet);
    expect(r.minted.map((m) => [m.symbol, m.amount, m.createdAccount])).toEqual([
      ['X', '1000000000', true],
      ['Y', '1000000000000', true],
    ]);
    expect(s.ch.balance(wallet, s.k.mx)).toBe(1_000_000_000n);
    expect(s.ch.balance(wallet, s.k.my)).toBe(1_000_000_000_000n);
    expect(r.nextClaimAt - r.at).toBe(DAY);
    expect((await s.info(wallet)).claim).toMatchObject({
      state: 'claimed',
      nextClaimAt: r.at + DAY,
      signature: r.signature,
    });
  });

  it('keeps an existing token account (CreateIdempotent) and reports it was not created', async () => {
    const s = setup();
    await s.faucet.check();
    const wallet = randomAddress();
    const ata = associatedTokenAddress(wallet, s.k.mx);
    s.ch.rpc.accounts.set(ata, { owner: TOKEN_PROGRAM_ID, data: new Uint8Array(165) });
    s.ch.rpc.tokenBalances.set(ata, { amount: 5n, decimals: 6 });
    const r = okResult(await s.claim(wallet));
    expect(r.minted.map((m) => m.createdAccount)).toEqual([false, true]);
    expect(s.ch.balance(wallet, s.k.mx)).toBe(1_000_000_005n);
  });

  it("applies SPL_FAUCET_AMOUNT in each mint's own decimals (MintToChecked carries them)", async () => {
    const s = setup({ amount: '2.5' });
    await s.faucet.check();
    const wallet = randomAddress();
    okResult(await s.claim(wallet));
    const d = decodeMessage(s.ch.rpc.sent[0]!.message);
    const mints = d.ixs.filter((i) => i.program === TOKEN_PROGRAM_ID);
    const amountOf = (data: Uint8Array) => new DataView(data.buffer, data.byteOffset).getBigUint64(1, true);
    expect(mints.map((i) => [i.accounts[0], amountOf(i.data), i.data[9]])).toEqual([
      [s.k.mx, 2_500_000n, 6],
      [s.k.my, 2_500_000_000n, 9],
    ]);
    expect(s.ch.balance(wallet, s.k.mx)).toBe(2_500_000n);
    // An amount finer than a mint's decimals, or past a u64, cannot be configured.
    const reg = new BridgeRegistry('undeployed', s.ch.rpc.genesisHash, [entry('Z', s.k.mx, 0)]);
    expect(() => faucetTokens(reg, new Map([[s.k.mx, s.k.x]]), '0.5')).toThrow(FaucetConfigError);
    expect(() => faucetTokens(reg, new Map([[s.k.mx, s.k.x]]), '18446744073709551616')).toThrow(/u64/);
  });

  it('refuses a wallet that is not a Solana address', async () => {
    const s = setup();
    await s.faucet.check();
    expect((await post(s.h, 'spl-faucet', { payload: { wallet: 'not a key' } })).status).toBe(400);
    const r = await s.claim('z'.repeat(44)); // base58, but not 32 bytes
    expect(r).toMatchObject({ status: 400, error: { code: 'spl-faucet-bad-wallet' } });
    expect(s.ch.rpc.sent).toHaveLength(0);
  });
});

describe('the test SPL faucet: mainnet-beta', () => {
  it('a registry on mainnet-beta: off for good, before any RPC call; no claim is admitted', async () => {
    const ch = mockChain(SOLANA_MAINNET_BETA_GENESIS_HASH);
    const s = setup({ chain: ch, registryGenesis: SOLANA_MAINNET_BETA_GENESIS_HASH });
    expect(s.faucet.current).toMatchObject({ kind: 'off', reason: 'mainnet', final: true });
    expect(await s.faucet.check()).toMatchObject({ reason: 'mainnet' });
    expect(ch.rpc.calls).toEqual([]);
    expect(await s.info()).toMatchObject({ enabled: false, reason: 'mainnet' });
    const r = await s.claim(randomAddress());
    expect(r).toMatchObject({ status: 403, error: { code: 'spl-faucet-off', detail: 'mainnet' } });
    expect(r.error!.message).toMatch(/never enabled on Solana mainnet/);
    expect(ch.rpc.sent).toHaveLength(0);
  });

  it("an RPC answering mainnet-beta's genesis hash: off for good, even if the RPC later changes", async () => {
    const ch = mockChain(SOLANA_MAINNET_BETA_GENESIS_HASH);
    // The registry names a test cluster; the RPC is mainnet-beta's.
    const s = setup({ chain: ch, registryGenesis: encodeKey(new Uint8Array(32).fill(7)) });
    expect(await s.faucet.check()).toMatchObject({ kind: 'off', reason: 'mainnet', final: true });
    const calls = ch.rpc.calls.length;
    const r = await s.claim(randomAddress());
    expect(r).toMatchObject({ status: 403, error: { code: 'spl-faucet-off', detail: 'mainnet' } });
    expect(ch.rpc.calls.length).toBe(calls); // final: never checked again
    expect(ch.rpc.sent).toHaveLength(0);
  });

  it("an RPC of another cluster than the registry's: refused as wrong-cluster", async () => {
    const s = setup({ registryGenesis: encodeKey(new Uint8Array(32).fill(1)) });
    expect(await s.faucet.check()).toMatchObject({ kind: 'off', reason: 'wrong-cluster', final: false });
    expect(await s.claim(randomAddress())).toMatchObject({ status: 503, error: { detail: 'wrong-cluster' } });
  });
});

describe('the test SPL faucet: only I-1 mints, each with its own authority', () => {
  it('parseFaucetKeys refuses a mint that is not in the journey registry, and malformed keys', () => {
    const k = newKey();
    const mint = randomAddress();
    const file = (m: string, key: unknown) => JSON.stringify({ [m]: key });
    expect(parseFaucetKeys(file(mint, Array.from(k.secretKey)), new Set([mint])).get(mint)?.publicKey).toBe(
      k.publicKey,
    );
    const other = randomAddress();
    expect(() => parseFaucetKeys(file(other, Array.from(k.secretKey)), new Set([mint]))).toThrow(
      new FaucetKeysError(
        `SPL_FAUCET_KEYS_FILE names the mint ${other}, which is not in the journey registry (BRIDGE_REGISTRY_FILE): the faucet mints only the registry's tokens`,
      ),
    );
    expect(() => parseFaucetKeys(file(mint, Array.from(k.secretKey).slice(0, 32)), new Set([mint]))).toThrow(
      /64 bytes/,
    );
    const swapped = Uint8Array.from(k.secretKey);
    swapped.set(newKey().secretKey.slice(32), 32);
    expect(() => parseFaucetKeys(file(mint, Array.from(swapped)), new Set([mint]))).toThrow(/inconsistent/);
    expect(() => parseFaucetKeys('{', new Set([mint]))).toThrow(/not JSON/);
    expect(() => parseFaucetKeys('{}', new Set([mint]))).toThrow(/names no mint/);
    expect(() => parseFaucetKeys(file('not-a-key', Array.from(k.secretKey)), new Set([mint]))).toThrow(/base58/);
  });

  it('the claim transaction names only registry mints and only faucet signers', () => {
    const s = setup();
    const wallet = randomAddress();
    const { payer, instructions } = claimInstructions(s.faucet.tokens, wallet);
    expect(payer).toBe(s.k.x.publicKey);
    expect(instructions.map((i) => i.programId)).toEqual([
      ASSOCIATED_TOKEN_PROGRAM_ID,
      TOKEN_PROGRAM_ID,
      ASSOCIATED_TOKEN_PROGRAM_ID,
      TOKEN_PROGRAM_ID,
    ]);
    const signers = new Set(instructions.flatMap((i) => i.keys.filter((k) => k.isSigner).map((k) => k.pubkey)));
    expect([...signers].sort()).toEqual([s.k.x.publicKey, s.k.y.publicKey].sort());
  });

  it('an authority mismatch at the check: refused (503, authority-mismatch), nothing sent', async () => {
    const s = setup();
    s.ch.rpc.accounts.set(s.k.my, { owner: TOKEN_PROGRAM_ID, data: mintData(randomAddress(), 9) });
    expect(await s.faucet.check()).toMatchObject({ kind: 'off', reason: 'authority-mismatch' });
    expect(await s.info()).toMatchObject({ enabled: false, reason: 'authority-mismatch' });
    const r = await s.claim(randomAddress());
    expect(r).toMatchObject({ status: 503, error: { code: 'spl-faucet-off', detail: 'authority-mismatch' } });
    expect(s.ch.rpc.sent).toHaveLength(0);
  });

  it('an authority that changes AFTER admission: the claim is checked again, refused, nothing sent, the wallet may claim again', async () => {
    const s = setup();
    await s.faucet.check();
    const wallet = randomAddress();
    const original = s.ch.rpc.accounts.get(s.k.mx)!;
    // Admitted while the authority is the held key...
    const admitted = await s.faucet.admit({ wallet }, 'c1');
    expect(admitted.ok).toBe(true);
    // ...then the mint authority moves before the job runs.
    s.ch.rpc.accounts.set(s.k.mx, { owner: TOKEN_PROGRAM_ID, data: mintData(randomAddress(), 6) });
    const ctx = {
      requestId: '0'.repeat(32),
      log: silentLog(),
      stage: () => {},
      prove: <T>(f: () => Promise<T>) => f(),
    };
    await expect(s.faucet.executor()({ wallet }, ctx)).rejects.toMatchObject({ code: 'spl-faucet-off' });
    expect(s.ch.rpc.sent).toHaveLength(0);
    expect(s.claims.get(wallet)).toBeUndefined();
    expect(s.faucet.current).toMatchObject({ kind: 'off', reason: 'authority-mismatch' });
    // Fixed on chain: the faucet re-checks on demand and the same wallet claims.
    s.ch.rpc.accounts.set(s.k.mx, original);
    okResult(await s.claim(wallet));
  });

  it('a mint that is Token-2022, missing, or of other decimals: refused as mint-mismatch', async () => {
    for (const bad of [
      { owner: 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb', data: undefined as Uint8Array | undefined },
      null,
      { owner: TOKEN_PROGRAM_ID, data: undefined },
    ]) {
      const s = setup();
      if (bad === null) s.ch.rpc.accounts.delete(s.k.mx);
      else s.ch.rpc.accounts.set(s.k.mx, { owner: bad.owner, data: bad.data ?? mintData(s.k.x.publicKey, 8) });
      expect(await s.faucet.check()).toMatchObject({ kind: 'off', reason: 'mint-mismatch' });
    }
  });

  it('the one transaction must fit a Solana packet: too many mints is a configuration error', () => {
    const ch = mockChain();
    const keys = new Map<string, FaucetKey>();
    const entries: BridgeEntry[] = [];
    for (let i = 0; i < 10; i++) {
      const m = randomAddress();
      keys.set(m, newKey());
      entries.push(entry(`T${i}`, m, 6));
    }
    expect(
      () =>
        new SplFaucet({
          registry: new BridgeRegistry('undeployed', ch.rpc.genesisHash, entries),
          keys,
          rpc: new FaucetSolanaRpc('http://solana-rpc.test', ch.fetch),
          claims: new SplFaucetClaims({ file: null, periodSeconds: DAY }),
          amountWhole: '1000',
          periodSeconds: DAY,
          claimsPerPeriod: 10,
          perClientPerPeriod: 3,
          log: silentLog(),
        }),
    ).toThrow(/over Solana's 1232/);
  });
});

describe('the test SPL faucet: once per wallet per period', () => {
  it('a second claim within 24 h is refused (429, Retry-After), and allowed once the period has passed', async () => {
    const s = setup();
    await s.faucet.check();
    const wallet = randomAddress();
    const first = okResult(await s.claim(wallet));
    s.clock.now += 3600;
    const again = await s.claim(wallet);
    expect(again).toMatchObject({ status: 429, error: { code: 'spl-faucet-period' } });
    expect(Number(again.retryAfter)).toBe(DAY - 3600);
    expect(again.error!.message).toMatch(/next claim opens at/);
    expect(s.ch.rpc.sent).toHaveLength(1);
    s.clock.now = first.at + DAY;
    okResult(await s.claim(wallet));
    expect(s.ch.balance(wallet, s.k.mx)).toBe(2_000_000_000n);
  });

  it('two requests for one wallet at once: the second is refused while the first is in progress', async () => {
    const s = setup();
    await s.faucet.check();
    const wallet = randomAddress();
    const a = await s.faucet.admit({ wallet }, 'c1');
    expect(a.ok).toBe(true);
    expect(await s.faucet.admit({ wallet }, 'c2')).toMatchObject({
      ok: false,
      status: 409,
      code: 'spl-faucet-pending',
    });
    // Sent at the same moment (both still awaiting their checks): exactly one is admitted.
    const other = randomAddress();
    const both = await Promise.all([s.faucet.admit({ wallet: other }, 'c3'), s.faucet.admit({ wallet: other }, 'c4')]);
    expect(both.map((o) => o.ok).sort()).toEqual([false, true]);
    expect(both.find((o) => !o.ok)).toMatchObject({ status: 409, code: 'spl-faucet-pending' });
  });

  it('a refused send (preflight) mints nothing and gives the claim back', async () => {
    const s = setup();
    await s.faucet.check();
    const wallet = randomAddress();
    s.ch.refuse = 'Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.';
    const r = await s.claim(wallet);
    expect('job' in r && r.job!.state).toBe('failed');
    expect('job' in r && r.job!.error).toMatchObject({ code: 'spl-faucet-failed' });
    expect(s.claims.get(wallet)).toBeUndefined();
    s.ch.refuse = null;
    okResult(await s.claim(wallet));
  });
});

describe('the test SPL faucet: the claims survive a restart', () => {
  it('a claimed wallet is still refused by a new relay on the same RELAY_DATA_DIR', async () => {
    const dir = tempDir();
    const file = join(dir, 'spl-faucet-claims.json');
    const clock = { now: 1_800_000_000 };
    const s1 = setup({ file, clock });
    await s1.faucet.check();
    const wallet = randomAddress();
    okResult(await s1.claim(wallet));
    expect(statSync(file).mode & 0o777).toBe(0o600);
    const onDisk = JSON.parse(readFileSync(file, 'utf8')) as { claims: Record<string, { state: string }> };
    expect(onDisk.claims[wallet]?.state).toBe('claimed');
    // A restart: a new store and faucet on the same file and the same chain and keys.
    const s2 = setup({ file, clock, chain: s1.ch, keys: s1.k });
    await s2.faucet.check();
    clock.now += 60;
    expect(await s2.claim(wallet)).toMatchObject({ status: 429, error: { code: 'spl-faucet-period' } });
    expect((await s2.info(wallet)).claim).toMatchObject({ state: 'claimed' });
    expect(s1.ch.rpc.sent).toHaveLength(1);
  });

  it('a claim sent but not confirmed stays pending across a restart, then is settled on chain', async () => {
    const dir = tempDir();
    const file = join(dir, 'spl-faucet-claims.json');
    const clock = { now: 1_800_000_000 };
    // Few polls: the mock moves its block height on with every call, and the blockhash must stay valid here.
    const s1 = setup({ file, clock, pollMs: 40, confirmTimeoutMs: 100 });
    await s1.faucet.check();
    const wallet = randomAddress();
    s1.ch.drop = true; // accepted by the RPC, never lands
    const r = await s1.claim(wallet);
    expect('job' in r && r.job!.error).toMatchObject({ code: 'spl-faucet-pending' });
    expect(s1.claims.get(wallet)).toMatchObject({ state: 'pending' });
    s1.ch.drop = false;
    // A new relay: the record is still there; while its blockhash may still land, the wallet waits.
    const s2 = setup({ file, clock, chain: s1.ch, keys: s1.k });
    await s2.faucet.check();
    expect(await s2.claim(wallet)).toMatchObject({ status: 409, error: { code: 'spl-faucet-pending' } });
    // Past its last valid block height it can never land: released, and the wallet claims at once.
    s1.ch.rpc.advanceBlockHeight(1000);
    const ok = okResult(await s2.claim(wallet));
    expect(s1.ch.balance(wallet, s1.k.mx)).toBe(1_000_000_000n);
    expect(ok.signature).not.toBe('');
  });

  it('a pending claim that DID land is recorded as claimed (no second mint)', async () => {
    const dir = tempDir();
    const file = join(dir, 'spl-faucet-claims.json');
    const s1 = setup({ file });
    await s1.faucet.check();
    const wallet = randomAddress();
    // The send's answer is lost (the RPC is unreachable after the send), but the transaction landed.
    const real = s1.ch.fetch;
    let sends = 0;
    const flaky = setup({
      file,
      chain: {
        ...s1.ch,
        fetch: async (url: string, init: RequestInit) => {
          const res = await real(url, init);
          if (String(init.body ?? '').includes('"sendTransaction"')) {
            sends++;
            throw new TypeError('fetch failed'); // the answer never arrives
          }
          return res;
        },
      },
      keys: s1.k,
    });
    await flaky.faucet.check();
    const r = await flaky.claim(wallet);
    expect(sends).toBe(1);
    expect('job' in r && r.job!.state).toBe('failed');
    expect(flaky.claims.get(wallet)).toMatchObject({ state: 'pending' });
    expect(s1.ch.balance(wallet, s1.k.mx)).toBe(1_000_000_000n);
    // The next request (a restarted relay) reconciles it: claimed, so refused for the period; nothing re-sent.
    const s3 = setup({ file, chain: s1.ch, keys: s1.k });
    await s3.faucet.check();
    expect(await s3.claim(wallet)).toMatchObject({ status: 429, error: { code: 'spl-faucet-period' } });
    expect(s1.ch.rpc.sent).toHaveLength(1);
  });

  it('a claims file that does not parse stops the faucet rather than forgetting every claim', () => {
    const dir = tempDir();
    const file = join(dir, 'spl-faucet-claims.json');
    writeFileSync(file, '{ not json');
    expect(() => new SplFaucetClaims({ file, periodSeconds: DAY })).toThrow(/cannot be read/);
  });
});

describe('the test SPL faucet: unsigned, charged to the client only (the C2 pattern)', () => {
  it("a claim naming a victim wallet does not touch the victim's owner rate limit", async () => {
    const s = setup();
    await s.faucet.check();
    // The victim's device key IS its Solana wallet: claims naming it are sent from another client.
    const victim = newWallet();
    const victimWallet = encodeKey(Uint8Array.from(Buffer.from(victim.deviceKey, 'hex')));
    s.client.address = '203.0.113.9';
    okResult(await s.claim(victimWallet));
    for (let i = 0; i < 3; i++)
      expect([409, 429]).toContain((await post(s.h, 'spl-faucet', { payload: { wallet: victimWallet } })).status);
    // The victim's own signed actions are still admitted up to its full per-owner limit.
    s.client.address = '198.51.100.7';
    const statuses: number[] = [];
    for (let i = 0; i < s.h.config.limits.actionsPerOwnerPerMinute; i++)
      statuses.push((await post(s.h, 'register', await signedBody(s.h, 'register', victim))).status);
    expect(statuses.every((st) => st === 202)).toBe(true);
    // And the claims gave the tokens to the victim's wallet: the only effect of naming it.
    expect(s.ch.balance(victimWallet, s.k.mx)).toBe(1_000_000_000n);
  });

  it('per client: at most SPL_FAUCET_PER_CLIENT_PER_PERIOD wallets; another client is unaffected', async () => {
    const s = setup({ perClient: 2 });
    await s.faucet.check();
    s.client.address = '203.0.113.20';
    okResult(await s.claim(randomAddress()));
    okResult(await s.claim(randomAddress()));
    expect(await s.claim(randomAddress())).toMatchObject({ status: 429, error: { code: 'spl-faucet-cap' } });
    s.client.address = '203.0.113.21';
    okResult(await s.claim(randomAddress()));
  });

  it('per period: at most SPL_FAUCET_CLAIMS_PER_PERIOD claims across all wallets', async () => {
    const s = setup({ cap: 1, perClient: 10 });
    await s.faucet.check();
    okResult(await s.claim(randomAddress()));
    s.client.address = '203.0.113.30';
    expect(await s.claim(randomAddress())).toMatchObject({ status: 429, error: { code: 'spl-faucet-cap' } });
  });

  it('per minute: unsigned requests have their own per-client budget (RATE_LIMIT_UNAUTHENTICATED_PER_MIN)', async () => {
    const s = setup({ perClient: 100 });
    await s.faucet.check();
    const statuses: number[] = [];
    for (let i = 0; i < s.h.config.limits.unauthenticatedPerMinute + 1; i++)
      statuses.push((await post(s.h, 'spl-faucet', { payload: { wallet: randomAddress() } })).status);
    expect(statuses.slice(0, 5).every((st) => st === 202)).toBe(true);
    expect(statuses.at(-1)).toBe(429);
  });
});

describe('the test SPL faucet: the keys never reach a log, a result, a refusal or the offer', () => {
  it('a full run (claim, refusals, an authority mismatch, a refused send) logs no form of any key', async () => {
    const log = silentLog();
    const s = setup({ log });
    const forms = [...secretForms(s.k.x), ...secretForms(s.k.y)];
    await s.faucet.check();
    const outputs: string[] = [];
    const wallet = randomAddress();
    outputs.push(JSON.stringify(await s.claim(wallet)));
    outputs.push(JSON.stringify(await s.claim(wallet)));
    outputs.push(JSON.stringify(await s.info(wallet)));
    s.ch.refuse = 'Transaction simulation failed: a test refusal';
    outputs.push(JSON.stringify(await s.claim(randomAddress())));
    s.ch.refuse = null;
    s.ch.rpc.accounts.set(s.k.my, { owner: TOKEN_PROGRAM_ID, data: mintData(randomAddress(), 9) });
    await s.faucet.check();
    outputs.push(JSON.stringify(await s.claim(randomAddress())));
    const everything = [...log.lines, ...s.h.log.lines, ...outputs].join('\n');
    expect(log.lines.length + s.h.log.lines.length).toBeGreaterThan(0);
    for (const f of forms) expect(everything).not.toContain(f);
  });

  it('config errors about the keys file never echo it', () => {
    const k = newKey();
    const forms = secretForms(k);
    const mint = randomAddress();
    for (const text of [
      JSON.stringify({ [mint]: Array.from(k.secretKey) }), // a mint not in the registry
      JSON.stringify({ [mint]: Array.from(k.secretKey).slice(0, 63) }),
      `${JSON.stringify({ [mint]: Array.from(k.secretKey) })} trailing`,
    ]) {
      let message = '';
      try {
        parseFaucetKeys(text, new Set([randomAddress()]));
      } catch (e) {
        message = (e as Error).message;
      }
      expect(message).not.toBe('');
      for (const f of forms) expect(message).not.toContain(f);
    }
  });

  it('the redactor main.ts sets up cuts every form of a key out of a line that would carry one', () => {
    const k = newKey();
    const r = new Redactor();
    for (const f of secretForms(k)) r.addSecret(f);
    const lines: string[] = [];
    const log = createLogger({ redactor: r, sink: (l) => lines.push(l) });
    for (const f of secretForms(k)) log.error(`oops ${f}`, { detail: `x${f}x` });
    for (const f of secretForms(k)) expect(lines.join('\n')).not.toContain(f);
  });
});

describe('the test SPL faucet: configuration', () => {
  const journey = JSON.parse(
    readFileSync(join(__dirname, '../../test/fixtures/journey-registry.undeployed.json'), 'utf8'),
  ) as { tokens: { colour: string; symbol: string; decimals: number; splMint: string }[] };
  const tokens = {
    mode: 'replace',
    tokens: journey.tokens.map((t) => ({ symbol: t.symbol, decimals: t.decimals, midnightColour: t.colour })),
  };
  const kx = newKey();
  const keysFile = (o: Record<string, unknown> = { [journey.tokens[0]!.splMint]: Array.from(kx.secretKey) }) =>
    JSON.stringify(o);
  const load = (env: Record<string, string>, files: Record<string, string> = {}, mode = 0o100600) =>
    loadConfig(
      {
        RELAY_NETWORK: 'undeployed',
        TOKENS_FILE: '/tokens.json',
        MIDNIGHT_MANAGED_PATH: '/keys',
        BRIDGE_REGISTRY_FILE: '/journey.json',
        RELAY_DATA_DIR: '/data',
        SPL_FAUCET_RPC_URL: 'http://127.0.0.1:18899',
        SPL_FAUCET_KEYS_FILE: '/faucet.json',
        ...env,
      },
      (p) => {
        const all: Record<string, string> = {
          '/tokens.json': JSON.stringify(tokens),
          '/journey.json': JSON.stringify(journey),
          '/faucet.json': keysFile(),
          ...files,
        };
        if (!(p in all)) throw new Error(`no ${p}`);
        return all[p]!;
      },
      { fileMode: () => mode },
    );
  const refusal = (fn: () => unknown): string => {
    try {
      fn();
      return 'started';
    } catch (e) {
      if (!(e instanceof ConfigError)) throw e;
      return e.message;
    }
  };

  it('the defaults: 1,000 whole tokens, once per 24 h; the keys come back as secrets only', () => {
    const { config, secrets } = load({});
    expect(config.splFaucet).toMatchObject({
      amountWhole: '1000',
      periodHours: 24,
      claimsFile: '/data/spl-faucet-claims.json',
    });
    const text = JSON.stringify(config, (_k, v: unknown) => (typeof v === 'bigint' ? v.toString() : v));
    for (const f of secretForms(kx)) expect(text).not.toContain(f);
    expect(secrets.splFaucetKeys?.get(journey.tokens[0]!.splMint)?.publicKey).toBe(kx.publicKey);
  });

  it('not configured without SPL_FAUCET_KEYS_FILE', () => {
    expect(load({ SPL_FAUCET_KEYS_FILE: '' }).config.splFaucet).toBeNull();
  });

  it('a mint not in the journey registry: refused, naming it', () => {
    const other = randomAddress();
    expect(refusal(() => load({}, { '/faucet.json': keysFile({ [other]: Array.from(kx.secretKey) }) }))).toMatch(
      new RegExp(`names the mint ${other}, which is not in the journey registry`),
    );
  });

  it('refuses a keys file readable by group or others, and the settings it needs', () => {
    expect(modeTooOpen(0o100600)).toBe(false);
    expect(modeTooOpen(0o100400)).toBe(false);
    expect(refusal(() => load({}, {}, 0o100644))).toMatch(/chmod 600/);
    expect(refusal(() => load({}, {}, 0o100640))).toMatch(/chmod 600/);
    expect(refusal(() => load({ BRIDGE_REGISTRY_FILE: '' }))).toMatch(/needs BRIDGE_REGISTRY_FILE/);
    expect(refusal(() => load({ RELAY_DATA_DIR: '' }))).toMatch(/needs RELAY_DATA_DIR/);
    expect(refusal(() => load({ SPL_FAUCET_RPC_URL: '' }))).toMatch(/needs SPL_FAUCET_RPC_URL/);
    expect(refusal(() => load({ SPL_FAUCET_RPC_URL: 'ftp://x' }))).toMatch(/not an http/);
    expect(refusal(() => load({ SPL_FAUCET_AMOUNT: '0' }))).toMatch(/positive decimal/);
    expect(refusal(() => load({ SPL_FAUCET_AMOUNT: '-5' }))).toMatch(/positive decimal/);
    expect(refusal(() => load({ SPL_FAUCET_PERIOD_H: '0' }))).toMatch(/SPL_FAUCET_PERIOD_H/);
  });

  it('a real mode-600 file passes the check main.ts runs (stat)', () => {
    const dir = tempDir();
    const f = join(dir, 'faucet.json');
    writeFileSync(f, keysFile(), { mode: 0o600 });
    expect(modeTooOpen(statSync(f).mode)).toBe(false);
    chmodSync(f, 0o644);
    expect(modeTooOpen(statSync(f).mode)).toBe(true);
  });
});

describe('the harness tool (relay/src/tools/spl-faucet-keys.ts, P13.3)', () => {
  it('matches each registry mint to the keypair that is its on-chain authority, and the file loads', async () => {
    const ch = mockChain();
    const k = { x: newKey(), y: newKey(), mx: randomAddress(), my: randomAddress() };
    ch.rpc.accounts.set(k.mx, { owner: TOKEN_PROGRAM_ID, data: mintData(k.x.publicKey, 6) });
    ch.rpc.accounts.set(k.my, { owner: TOKEN_PROGRAM_ID, data: mintData(k.y.publicKey, 9) });
    const journey = {
      midnightNetwork: 'undeployed',
      solanaGenesisHash: ch.rpc.genesisHash,
      tokens: [entry('X', k.mx, 6), entry('Y', k.my, 9)],
    };
    const rpc = new FaucetSolanaRpc('http://solana-rpc.test', ch.fetch);
    // Given in any order, with an unrelated key too.
    const plan = await planKeysFile({ journey, keypairs: [newKey().secretKey, k.y.secretKey, k.x.secretKey], rpc });
    expect(plan.missing).toEqual([]);
    expect(plan.report).toEqual([`X ${k.mx}: authority ${k.x.publicKey}`, `Y ${k.my}: authority ${k.y.publicKey}`]);
    for (const f of [...secretForms(k.x), ...secretForms(k.y)]) expect(plan.report.join('\n')).not.toContain(f);
    const loaded = parseFaucetKeys(keysFileText(plan.keys), new Set([k.mx, k.my]));
    expect(loaded.get(k.mx)?.publicKey).toBe(k.x.publicKey);
    expect(loaded.get(k.my)?.publicKey).toBe(k.y.publicKey);
    // Without Y's authority: Y is missing (the CLI refuses, exit 65, unless --allow-partial).
    const partial = await planKeysFile({ journey, keypairs: [k.x.secretKey], rpc });
    expect(partial.missing).toEqual([k.my]);
    expect([...partial.keys.keys()]).toEqual([k.mx]);
  });
});
