// GENERATED by scripts/pin-account-keys.ts from a relay key volume. Do not edit by hand: run
//   bun scripts/pin-account-keys.ts <key-volume-root>
// whenever the key set changes (plan P9.I).
//
// The verifier keys of a Night Market account, as this web build expects them on chain (AA 00047
// P9.S, questions Q26): circuit → SHA-256 of its verifier key. The browser refuses to deposit to,
// trade from or seal an entry for an account whose on-chain operations are not exactly these.

export const PINNED_ACCOUNT_KEYS = {
  /** The relay key volume's fingerprint these were taken from (RELAY_KEYS_FINGERPRINT). */
  keySet: 'a627edb18f6aa54c48194ee9fb38b89140887cfc56b0efb377c9504b79edda92',
  /** The acedward/passport commit the key set was compiled from. */
  passportCommit: '451f7610e90000e0c5550877418122a04b85d0e6',
  circuits: {
    activate_initial_device_with_ed25519: '883151b8b20534627a7938624f2f8f681ab659673cc43d22ddbfd0e4848c8110',
    add_device_with_ed25519: '69c9d015b6416eb0b1b9a4534a98621f4bcb0d7899e781f6ce65a7561d5c4b66',
    append_inbox_with_ed25519: '9dc6780e376c937669803e20e421e98e92bebb7507f9ab552d10e5126e9abbef',
    deposit_shielded: '6761a2e9cb905a115e7705b63b7df57b3c14dfa39fa48411ff6f512b8ff916b3',
    deposit_unshielded: '3deb950234a50b1515d496d687bd173118cf2e7461ab02d63270dbbd5ac5a973',
    open_swap_shielded_with_ed25519: 'ff9d9b687906fea423a1a9e7527aa65d397170cb8132ce712e431bbea1db6696',
    remove_device_with_ed25519: 'a7cca7a173f3b4c244b56265f273c05530d8937bbcef1abd817605810820950e',
    rotate_enc_key_with_ed25519: '6199d27c69d3da2899aa3c4444305716685c26a1b8f2c22ffe9990055f1e75b2',
    withdraw_shielded_to_contract_with_ed25519: '24abdca52084d92ae64f78cfe91318e7a6ca16100d76226cc2dfffa901a03a7e',
    withdraw_shielded_with_ed25519: '35eeb8eb2ca14c2252486cd642165479b50adfe90c2f1f7a25485385c1b0813b',
    withdraw_unshielded_with_ed25519: '1f8e9b9f15d2796185e9bb0ce95be2324a9cf3095697160260716f7bca4ccb45',
  },
} as const;
