// GENERATED by scripts/pin-account-keys.ts from a relay key volume. Do not edit by hand: run
//   bun scripts/pin-account-keys.ts <key-volume-root>
// whenever the key set changes (plan P9.I).
//
// The verifier keys of a Night Market account, as this web build expects them on chain (AA 00047
// P9.S, questions Q26): circuit → SHA-256 of its verifier key. The browser refuses to deposit to,
// trade from or seal an entry for an account whose on-chain operations are not exactly these.

export const PINNED_ACCOUNT_KEYS = {
  /** The relay key volume's fingerprint these were taken from (RELAY_KEYS_FINGERPRINT). */
  keySet: 'efc52fbc1aa2a8cb22327b1c55c820c83b2ded2e383d9ca3afeaab666e6bef7f',
  /** The acedward/passport commit the key set was compiled from. */
  passportCommit: 'b2f1847271435d37c441966271aa8e20c9b09ecf',
  circuits: {
    activate_initial_device_with_ed25519: '883151b8b20534627a7938624f2f8f681ab659673cc43d22ddbfd0e4848c8110',
    append_inbox_with_ed25519: 'd13f69820546291f7afa916d7d4bd2bb630efaeeac330ce9fadd93541f403701',
    deposit_shielded: '6761a2e9cb905a115e7705b63b7df57b3c14dfa39fa48411ff6f512b8ff916b3',
    deposit_unshielded: '3deb950234a50b1515d496d687bd173118cf2e7461ab02d63270dbbd5ac5a973',
    open_swap_shielded_with_ed25519: '4794a0e3c6c87da4a5b49fc1a4502691ba452bbb9460cd246e569da14fb72eeb',
    rotate_enc_key_with_ed25519: 'd3c0cfb87d19be79cfb62e8aedb2d2009ace4f9f7e76e30d20a7de4ad933babe',
    withdraw_shielded_to_contract_with_ed25519: '4ed29c43fb52744927830cbbe0bf33bb9d50722ae268806f10292ded8057e34b',
    withdraw_shielded_with_ed25519: '41a81b9255b57127555534026491d345aba6998f3497b6b79fbce3bf7c7fc316',
    withdraw_unshielded_with_ed25519: '7123727581e745741349fff384b9aec0308a93363bac6db262781098a9361a52',
  },
} as const;
