#!/usr/bin/env bun
// Pin the market account's verifier keys in the WEB build (AA 00047 P9.S; questions Q26 and Q31).
//
// The browser checks every account it deposits to or trades from against the public indexer: the
// account must carry exactly the market's circuits, each with the verifier key of the key set the
// market deploys with (spec FR-005, now in the browser too). This script writes those digests from a
// relay key volume (the same files the relay's `RELAY_KEYS_FINGERPRINT` pins):
//
//   packages/core/src/passport/pinned-account-keys.ts   circuit → SHA-256(verifier key), for the build
//   test/fixtures/account-verifier-keys.json            the verifier keys themselves (public chain
//                                                       data), for the tests' mock indexer
//
// Run it whenever the key set changes (a new vendor/passport pin, a new compiler: plan P9.I):
//
//   bun scripts/pin-account-keys.ts <key-volume-root>      e.g. ~/.cache/aa-00047/b3-keys
//
// The circuits are the market shape (Track A's `ed25519AccountCircuits({ withSwap: true })`, the
// list relay/src/passport/account-shape.ts deploys); a key missing from the volume is an error.

import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import { ed25519AccountCircuits } from '../vendor/passport/contract/src/wallet/wave-deploy.js';

const root = process.argv[2];
if (!root) {
  console.error('usage: bun scripts/pin-account-keys.ts <key-volume-root>');
  process.exit(64);
}
const REPO = fileURLToPath(new URL('..', import.meta.url));
const keys = path.join(root, 'account', 'keys');
const report = path.join(root, '.night-market-keys.json');
const fingerprint = existsSync(report)
  ? String((JSON.parse(readFileSync(report, 'utf8')) as { fingerprint?: string }).fingerprint ?? '')
  : '';
const passportCommit = (() => {
  try {
    const p = JSON.parse(readFileSync(report, 'utf8')) as { build?: { passportCommit?: string } };
    return String(p.build?.passportCommit ?? '');
  } catch {
    return '';
  }
})();

const circuits = [...ed25519AccountCircuits({ withSwap: true })].sort();
const digests: Record<string, string> = {};
const vks: Record<string, string> = {};
for (const c of circuits) {
  const f = path.join(keys, `${c}.verifier`);
  if (!existsSync(f)) {
    console.error(`pin-account-keys: ${f} is missing (the key volume must hold every market circuit's verifier key)`);
    process.exit(66);
  }
  const bytes = readFileSync(f);
  digests[c] = createHash('sha256').update(bytes).digest('hex');
  vks[c] = bytes.toString('hex');
}

const ts = `// GENERATED by scripts/pin-account-keys.ts from a relay key volume. Do not edit by hand: run
//   bun scripts/pin-account-keys.ts <key-volume-root>
// whenever the key set changes (plan P9.I).
//
// The verifier keys of a Night Market account, as this web build expects them on chain (AA 00047
// P9.S, questions Q26): circuit → SHA-256 of its verifier key. The browser refuses to deposit to,
// trade from or seal an entry for an account whose on-chain operations are not exactly these.

export const PINNED_ACCOUNT_KEYS = {
  /** The relay key volume's fingerprint these were taken from (RELAY_KEYS_FINGERPRINT). */
  keySet: '${fingerprint}',
  /** The acedward/passport commit the key set was compiled from. */
  passportCommit: '${passportCommit}',
  circuits: {
${circuits.map((c) => `    ${c}: '${digests[c]}',`).join('\n')}
  },
} as const;
`;
writeFileSync(path.join(REPO, 'packages/core/src/passport/pinned-account-keys.ts'), ts);
writeFileSync(
  path.join(REPO, 'test/fixtures/account-verifier-keys.json'),
  JSON.stringify({ keySet: fingerprint, passportCommit, circuits: vks }, null, 2) + '\n',
);
console.log(`pinned ${circuits.length} circuits (key set ${fingerprint || 'unknown'})`);
